FROM influx6/midash

MAINTAINER Alexander Ewetumo <trinoxf@gmail.com>

# Dont ever do this, far better to load such secret through a 
# env files, but since this will be a plugic repo, then we will allow 
# this here.
ENV MYSQL_USER dbUser
ENV MYSQL_DATABASE midash
ENV MYSQL_PASSWORD !thunder#bot

CMD ["/bin/midash-bin"]